name: accordion/faq-block
typeName: accordion_faqblock
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true

  - identifier: text
    type: Text

  - identifier: textarea
    type: Textarea
    enableRichtext: true
    richtextConfiguration: full