name: my-vendor/contact
typeName: myvendor_contact
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true

  - identifier: phone
    type: Text
    label: Phone Number

  - identifier: email
    type: Email
    label: Email Address

  - identifier: address
    type: Textarea
    label: Address

  - identifier: map
    type: Textarea
    label: Map Embed Code (iframe)